services:
  db:
    image: postgres:16
    container_name: liberty-test-container-db
    restart: always
    environment:
      POSTGRES_USER: aki
      POSTGRES_PASSWORD: akipassword
      POSTGRES_DB: liberty-test-db
    ports:
      - "5432:5432"
    volumes:
      - liberty-test-data:/var/lib/postgresql/data

volumes:
  liberty-test-data:
